---
- name: Manage Ubuntu
  hosts: home
  become: yes
  roles:
    - role: ubuntu_update
      when: action == 'update'
    - role: ubuntu_shutdown
      when: action == 'shutdown'
    - role: ubuntu_install
      when: action == 'install'

